### ISSUE TITLE
Regarding RK2

### ISSUE THREAD

**Issue by Lasiace** [roycan/cs131_finals_2016#15]
I wanted to bring this up because it seems that both implementations (by Yao and Michael) have a few problems that I was hoping could be fixed so that I could use them.

Yao's implementation seems to work, but the fact that it requires a function class to be declared instead of just making a string makes it kind of harder and messier to use. It would also be good if the printing of the csv wasn't handled during calculations, since I don't actually want it to write that, especially since I'll be doing RK2 for many iterations and the csv would constantly be overwritten, making it kinda pointless.

These are less important, but it would also be nice if main was separated, although it's not 100% necessary since I can just avoid executing that. Also, the fact that it uses Vector instead of normal arrays or Lists is kinda weird, and feels unnecessary, but ultimately workable.

Michael's implementation also seems to work, but the fact that everything is done in a main method means that I can't actually _use_ it in my classes, especially since it doesn't return anything. I'm hoping that the calculations could be handled in a method separate from main so I could actually use said class. 

Also, its kinda strange and a bit confusing to have a class that stores variables and takes input, but does no calculations of any sort, with the main class doing all of it.

It would also be nice for the two implementations to use mxparser or other such parsing libraries instead so that they either don't require a class made specifically for the function, or aren't vulnerable to code injection.

But yeah that's about it. I'm hoping these issues can be fixed soon, so that I can get back to work on the project. Thank you for reading!

~Lyon

**Comment by roycan** [comment]
That's specific enough.  :)   Now take either one of the RK2 classes and implement improvements.  If you know enough Git to stage the commit for only the RK 2 files, then do a pull request to the master.  If not, just keep the improvements in your branch. 
Either way, please reply with a comment on what you got to work.

**Comment by roycan** [comment]
issue closed. do check.  great assesent of the RK 2 classes by the way
